/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **schema_migrations**
   * - Table in database
   */
  export namespace schema_migrations {
    export type Table = 'schema_migrations';
    export interface Selectable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
    version: string;
    }
    export interface JSONSelectable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
    version: string;
    }
    export interface Whereable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
    version?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
    version: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
    version?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'schema_migrations_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **User**
   * - Table in database
   */
  export namespace User {
    export type Table = 'User';
    export interface Selectable {
      /**
      * **User.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
    id: string;
      /**
      * **User.telegramId**
      * - `int8` in database
      * - `NOT NULL`, no default
      */
    telegramId: db.Int8String;
      /**
      * **User.googleRefreshToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleRefreshToken: string;
      /**
      * **User.googleAccessToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleAccessToken: string;
      /**
      * **User.googleExpiryDate**
      * - `timestamptz` in database
      * - `NOT NULL`, no default
      */
    googleExpiryDate: Date;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    createdAt: Date;
      /**
      * **User.updatedAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    updatedAt: Date;
    }
    export interface JSONSelectable {
      /**
      * **User.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
    id: string;
      /**
      * **User.telegramId**
      * - `int8` in database
      * - `NOT NULL`, no default
      */
    telegramId: number;
      /**
      * **User.googleRefreshToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleRefreshToken: string;
      /**
      * **User.googleAccessToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleAccessToken: string;
      /**
      * **User.googleExpiryDate**
      * - `timestamptz` in database
      * - `NOT NULL`, no default
      */
    googleExpiryDate: db.TimestampTzString;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    createdAt: db.TimestampTzString;
      /**
      * **User.updatedAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    updatedAt: db.TimestampTzString;
    }
    export interface Whereable {
      /**
      * **User.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
    id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **User.telegramId**
      * - `int8` in database
      * - `NOT NULL`, no default
      */
    telegramId?: (number | db.Int8String) | db.Parameter<(number | db.Int8String)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (number | db.Int8String) | db.Parameter<(number | db.Int8String)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **User.googleRefreshToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleRefreshToken?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **User.googleAccessToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleAccessToken?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **User.googleExpiryDate**
      * - `timestamptz` in database
      * - `NOT NULL`, no default
      */
    googleExpiryDate?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    createdAt?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **User.updatedAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    updatedAt?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **User.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
    id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **User.telegramId**
      * - `int8` in database
      * - `NOT NULL`, no default
      */
    telegramId: (number | db.Int8String) | db.Parameter<(number | db.Int8String)> | db.SQLFragment;
      /**
      * **User.googleRefreshToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleRefreshToken: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **User.googleAccessToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleAccessToken: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **User.googleExpiryDate**
      * - `timestamptz` in database
      * - `NOT NULL`, no default
      */
    googleExpiryDate: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    createdAt?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **User.updatedAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    updatedAt?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **User.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
    id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **User.telegramId**
      * - `int8` in database
      * - `NOT NULL`, no default
      */
    telegramId?: (number | db.Int8String) | db.Parameter<(number | db.Int8String)> | db.SQLFragment | db.SQLFragment<any, (number | db.Int8String) | db.Parameter<(number | db.Int8String)> | db.SQLFragment>;
      /**
      * **User.googleRefreshToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleRefreshToken?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **User.googleAccessToken**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    googleAccessToken?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **User.googleExpiryDate**
      * - `timestamptz` in database
      * - `NOT NULL`, no default
      */
    googleExpiryDate?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment>;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    createdAt?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **User.updatedAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    updatedAt?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'User_pkey' | 'User_telegramId_key';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = schema_migrations.Table | User.Table;
    export type Selectable = schema_migrations.Selectable | User.Selectable;
    export type JSONSelectable = schema_migrations.JSONSelectable | User.JSONSelectable;
    export type Whereable = schema_migrations.Whereable | User.Whereable;
    export type Insertable = schema_migrations.Insertable | User.Insertable;
    export type Updatable = schema_migrations.Updatable | User.Updatable;
    export type UniqueIndex = schema_migrations.UniqueIndex | User.UniqueIndex;
    export type Column = schema_migrations.Column | User.Column;
  
    export type AllBaseTables = [schema_migrations.Table, User.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [schema_migrations.Table, User.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Selectable;
    "User": User.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.JSONSelectable;
    "User": User.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Whereable;
    "User": User.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Insertable;
    "User": User.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Updatable;
    "User": User.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "schema_migrations": schema_migrations.UniqueIndex;
    "User": User.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Column;
    "User": User.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "schema_migrations": schema_migrations.SQL;
    "User": User.SQL;
  }[T];

}
