name: Release CI/CD

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: johnnycrazy/google-birthdays-bot
          tags: |
            type=ref,event=tag
      - name: Setup | Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Setup | Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build | Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
